apiVersion: apps/v1
kind: Deployment
metadata:
  name: carts-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: carts-api
  template:
    metadata:
      labels:
        app: carts-api
    spec:
      containers:
        - name: carts-api
          image: carts-api:v1
          imagePullPolicy: Never
          ports:
            - containerPort: 80